name: tficmobileapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.0.0
  http: ^1.3.0
  flutter_html: ^3.0.0-alpha.6
  intl: ^0.18.1
  firebase_core: ^2.32.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^19.1.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/TFICLOGOCIRCLE.png"
  adaptive_icon_background: "#0F0F1C"
  adaptive_icon_foreground: "assets/icon/tficlogocircle.png"

dependency_overrides:
  flutter_local_notifications_linux:
    git:
      url: https://github.com/MaikuB/flutter_local_notifications.git
      path: flutter_local_notifications_linux
      ref: master

flutter:
  uses-material-design: true
